// Code generated by protoc-gen-gogo.
// source: proto/ca_service.proto
// DO NOT EDIT!

/*
	Package istio_v1_auth is a generated protocol buffer package.

	It is generated from these files:
		proto/ca_service.proto

	It has these top-level messages:
		CertificateSignRequest
		NodeAgentCredentials
		GcpInstanceCredential
		CertificateSignResponse
*/
package istio_v1_auth

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_rpc "github.com/googleapis/googleapis/google/rpc"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CertificateSignRequest struct {
	Csr                  []byte                `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`
	NodeAgentCredentials *NodeAgentCredentials `protobuf:"bytes,2,opt,name=node_agent_credentials,json=nodeAgentCredentials" json:"node_agent_credentials,omitempty"`
}

func (m *CertificateSignRequest) Reset()                    { *m = CertificateSignRequest{} }
func (*CertificateSignRequest) ProtoMessage()               {}
func (*CertificateSignRequest) Descriptor() ([]byte, []int) { return fileDescriptorCaService, []int{0} }

type NodeAgentCredentials struct {
	// Types that are valid to be assigned to NodeCredential:
	//	*NodeAgentCredentials_GcpInstanceCredential
	NodeCredential isNodeAgentCredentials_NodeCredential `protobuf_oneof:"node_credential"`
}

func (m *NodeAgentCredentials) Reset()                    { *m = NodeAgentCredentials{} }
func (*NodeAgentCredentials) ProtoMessage()               {}
func (*NodeAgentCredentials) Descriptor() ([]byte, []int) { return fileDescriptorCaService, []int{1} }

type isNodeAgentCredentials_NodeCredential interface {
	isNodeAgentCredentials_NodeCredential()
	MarshalTo([]byte) (int, error)
	Size() int
}

type NodeAgentCredentials_GcpInstanceCredential struct {
	GcpInstanceCredential *GcpInstanceCredential `protobuf:"bytes,1,opt,name=gcp_instance_credential,json=gcpInstanceCredential,oneof"`
}

func (*NodeAgentCredentials_GcpInstanceCredential) isNodeAgentCredentials_NodeCredential() {}

func (m *NodeAgentCredentials) GetNodeCredential() isNodeAgentCredentials_NodeCredential {
	if m != nil {
		return m.NodeCredential
	}
	return nil
}

func (m *NodeAgentCredentials) GetGcpInstanceCredential() *GcpInstanceCredential {
	if x, ok := m.GetNodeCredential().(*NodeAgentCredentials_GcpInstanceCredential); ok {
		return x.GcpInstanceCredential
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*NodeAgentCredentials) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _NodeAgentCredentials_OneofMarshaler, _NodeAgentCredentials_OneofUnmarshaler, _NodeAgentCredentials_OneofSizer, []interface{}{
		(*NodeAgentCredentials_GcpInstanceCredential)(nil),
	}
}

func _NodeAgentCredentials_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*NodeAgentCredentials)
	// node_credential
	switch x := m.NodeCredential.(type) {
	case *NodeAgentCredentials_GcpInstanceCredential:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GcpInstanceCredential); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("NodeAgentCredentials.NodeCredential has unexpected type %T", x)
	}
	return nil
}

func _NodeAgentCredentials_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*NodeAgentCredentials)
	switch tag {
	case 1: // node_credential.gcp_instance_credential
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GcpInstanceCredential)
		err := b.DecodeMessage(msg)
		m.NodeCredential = &NodeAgentCredentials_GcpInstanceCredential{msg}
		return true, err
	default:
		return false, nil
	}
}

func _NodeAgentCredentials_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*NodeAgentCredentials)
	// node_credential
	switch x := m.NodeCredential.(type) {
	case *NodeAgentCredentials_GcpInstanceCredential:
		s := proto.Size(x.GcpInstanceCredential)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GcpInstanceCredential struct {
	SignedInstanceMetadata []byte `protobuf:"bytes,1,opt,name=signed_instance_metadata,json=signedInstanceMetadata,proto3" json:"signed_instance_metadata,omitempty"`
}

func (m *GcpInstanceCredential) Reset()                    { *m = GcpInstanceCredential{} }
func (*GcpInstanceCredential) ProtoMessage()               {}
func (*GcpInstanceCredential) Descriptor() ([]byte, []int) { return fileDescriptorCaService, []int{2} }

type CertificateSignResponse struct {
	IsApproved      bool               `protobuf:"varint,1,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"`
	Status          *google_rpc.Status `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	SignedCertChain []byte             `protobuf:"bytes,3,opt,name=signed_cert_chain,json=signedCertChain,proto3" json:"signed_cert_chain,omitempty"`
}

func (m *CertificateSignResponse) Reset()                    { *m = CertificateSignResponse{} }
func (*CertificateSignResponse) ProtoMessage()               {}
func (*CertificateSignResponse) Descriptor() ([]byte, []int) { return fileDescriptorCaService, []int{3} }

func init() {
	proto.RegisterType((*CertificateSignRequest)(nil), "istio_v1_auth.CertificateSignRequest")
	proto.RegisterType((*NodeAgentCredentials)(nil), "istio_v1_auth.NodeAgentCredentials")
	proto.RegisterType((*GcpInstanceCredential)(nil), "istio_v1_auth.GcpInstanceCredential")
	proto.RegisterType((*CertificateSignResponse)(nil), "istio_v1_auth.CertificateSignResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for IstioCAService service

type IstioCAServiceClient interface {
	// Request to sign a Certificate Signing Request.
	//
	// The CSR is generated on the Node Agent along with the private key. The Node
	// Agent also needs to provide its credentials so the CA can verify the Node
	// Agent requesting the credentials.
	Sign(ctx context.Context, in *CertificateSignRequest, opts ...grpc.CallOption) (*CertificateSignResponse, error)
}

type istioCAServiceClient struct {
	cc *grpc.ClientConn
}

func NewIstioCAServiceClient(cc *grpc.ClientConn) IstioCAServiceClient {
	return &istioCAServiceClient{cc}
}

func (c *istioCAServiceClient) Sign(ctx context.Context, in *CertificateSignRequest, opts ...grpc.CallOption) (*CertificateSignResponse, error) {
	out := new(CertificateSignResponse)
	err := grpc.Invoke(ctx, "/istio_v1_auth.IstioCAService/Sign", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IstioCAService service

type IstioCAServiceServer interface {
	// Request to sign a Certificate Signing Request.
	//
	// The CSR is generated on the Node Agent along with the private key. The Node
	// Agent also needs to provide its credentials so the CA can verify the Node
	// Agent requesting the credentials.
	Sign(context.Context, *CertificateSignRequest) (*CertificateSignResponse, error)
}

func RegisterIstioCAServiceServer(s *grpc.Server, srv IstioCAServiceServer) {
	s.RegisterService(&_IstioCAService_serviceDesc, srv)
}

func _IstioCAService_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IstioCAServiceServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/istio_v1_auth.IstioCAService/Sign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IstioCAServiceServer).Sign(ctx, req.(*CertificateSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IstioCAService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "istio_v1_auth.IstioCAService",
	HandlerType: (*IstioCAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sign",
			Handler:    _IstioCAService_Sign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ca_service.proto",
}

func (m *CertificateSignRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CertificateSignRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Csr) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintCaService(dAtA, i, uint64(len(m.Csr)))
		i += copy(dAtA[i:], m.Csr)
	}
	if m.NodeAgentCredentials != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintCaService(dAtA, i, uint64(m.NodeAgentCredentials.Size()))
		n1, err := m.NodeAgentCredentials.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *NodeAgentCredentials) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeAgentCredentials) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NodeCredential != nil {
		nn2, err := m.NodeCredential.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn2
	}
	return i, nil
}

func (m *NodeAgentCredentials_GcpInstanceCredential) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.GcpInstanceCredential != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintCaService(dAtA, i, uint64(m.GcpInstanceCredential.Size()))
		n3, err := m.GcpInstanceCredential.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}
func (m *GcpInstanceCredential) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GcpInstanceCredential) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.SignedInstanceMetadata) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintCaService(dAtA, i, uint64(len(m.SignedInstanceMetadata)))
		i += copy(dAtA[i:], m.SignedInstanceMetadata)
	}
	return i, nil
}

func (m *CertificateSignResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CertificateSignResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.IsApproved {
		dAtA[i] = 0x8
		i++
		if m.IsApproved {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Status != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintCaService(dAtA, i, uint64(m.Status.Size()))
		n4, err := m.Status.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if len(m.SignedCertChain) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintCaService(dAtA, i, uint64(len(m.SignedCertChain)))
		i += copy(dAtA[i:], m.SignedCertChain)
	}
	return i, nil
}

func encodeFixed64CaService(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32CaService(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintCaService(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CertificateSignRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Csr)
	if l > 0 {
		n += 1 + l + sovCaService(uint64(l))
	}
	if m.NodeAgentCredentials != nil {
		l = m.NodeAgentCredentials.Size()
		n += 1 + l + sovCaService(uint64(l))
	}
	return n
}

func (m *NodeAgentCredentials) Size() (n int) {
	var l int
	_ = l
	if m.NodeCredential != nil {
		n += m.NodeCredential.Size()
	}
	return n
}

func (m *NodeAgentCredentials_GcpInstanceCredential) Size() (n int) {
	var l int
	_ = l
	if m.GcpInstanceCredential != nil {
		l = m.GcpInstanceCredential.Size()
		n += 1 + l + sovCaService(uint64(l))
	}
	return n
}
func (m *GcpInstanceCredential) Size() (n int) {
	var l int
	_ = l
	l = len(m.SignedInstanceMetadata)
	if l > 0 {
		n += 1 + l + sovCaService(uint64(l))
	}
	return n
}

func (m *CertificateSignResponse) Size() (n int) {
	var l int
	_ = l
	if m.IsApproved {
		n += 2
	}
	if m.Status != nil {
		l = m.Status.Size()
		n += 1 + l + sovCaService(uint64(l))
	}
	l = len(m.SignedCertChain)
	if l > 0 {
		n += 1 + l + sovCaService(uint64(l))
	}
	return n
}

func sovCaService(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozCaService(x uint64) (n int) {
	return sovCaService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *CertificateSignRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CertificateSignRequest{`,
		`Csr:` + fmt.Sprintf("%v", this.Csr) + `,`,
		`NodeAgentCredentials:` + strings.Replace(fmt.Sprintf("%v", this.NodeAgentCredentials), "NodeAgentCredentials", "NodeAgentCredentials", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *NodeAgentCredentials) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&NodeAgentCredentials{`,
		`NodeCredential:` + fmt.Sprintf("%v", this.NodeCredential) + `,`,
		`}`,
	}, "")
	return s
}
func (this *NodeAgentCredentials_GcpInstanceCredential) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&NodeAgentCredentials_GcpInstanceCredential{`,
		`GcpInstanceCredential:` + strings.Replace(fmt.Sprintf("%v", this.GcpInstanceCredential), "GcpInstanceCredential", "GcpInstanceCredential", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GcpInstanceCredential) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GcpInstanceCredential{`,
		`SignedInstanceMetadata:` + fmt.Sprintf("%v", this.SignedInstanceMetadata) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CertificateSignResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CertificateSignResponse{`,
		`IsApproved:` + fmt.Sprintf("%v", this.IsApproved) + `,`,
		`Status:` + strings.Replace(fmt.Sprintf("%v", this.Status), "Status", "google_rpc.Status", 1) + `,`,
		`SignedCertChain:` + fmt.Sprintf("%v", this.SignedCertChain) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringCaService(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *CertificateSignRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCaService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CertificateSignRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CertificateSignRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Csr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCaService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCaService
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Csr = append(m.Csr[:0], dAtA[iNdEx:postIndex]...)
			if m.Csr == nil {
				m.Csr = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeAgentCredentials", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCaService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCaService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NodeAgentCredentials == nil {
				m.NodeAgentCredentials = &NodeAgentCredentials{}
			}
			if err := m.NodeAgentCredentials.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCaService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCaService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeAgentCredentials) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCaService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeAgentCredentials: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeAgentCredentials: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GcpInstanceCredential", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCaService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCaService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &GcpInstanceCredential{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.NodeCredential = &NodeAgentCredentials_GcpInstanceCredential{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCaService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCaService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GcpInstanceCredential) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCaService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GcpInstanceCredential: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GcpInstanceCredential: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedInstanceMetadata", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCaService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCaService
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedInstanceMetadata = append(m.SignedInstanceMetadata[:0], dAtA[iNdEx:postIndex]...)
			if m.SignedInstanceMetadata == nil {
				m.SignedInstanceMetadata = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCaService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCaService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CertificateSignResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCaService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CertificateSignResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CertificateSignResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsApproved", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCaService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsApproved = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCaService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCaService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &google_rpc.Status{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedCertChain", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCaService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCaService
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedCertChain = append(m.SignedCertChain[:0], dAtA[iNdEx:postIndex]...)
			if m.SignedCertChain == nil {
				m.SignedCertChain = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCaService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCaService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCaService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCaService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCaService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCaService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthCaService
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowCaService
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipCaService(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthCaService = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCaService   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("proto/ca_service.proto", fileDescriptorCaService) }

var fileDescriptorCaService = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xbf, 0x6f, 0x13, 0x31,
	0x18, 0x3d, 0x53, 0x54, 0xa1, 0x2f, 0x40, 0xa9, 0x95, 0x26, 0x51, 0x06, 0x53, 0x85, 0x1f, 0xaa,
	0x3a, 0x5c, 0x44, 0x58, 0xd8, 0x50, 0x9a, 0x01, 0x3a, 0x80, 0xc4, 0x45, 0x0c, 0x30, 0x70, 0x32,
	0xbe, 0x0f, 0xd7, 0x52, 0xb1, 0x8d, 0xed, 0x64, 0x66, 0x61, 0x60, 0x43, 0xfc, 0x15, 0xfc, 0x29,
	0x1d, 0x3b, 0x32, 0x92, 0x63, 0x61, 0xec, 0x9f, 0x80, 0xee, 0x7c, 0x28, 0x34, 0x9c, 0xc4, 0x66,
	0xbd, 0xf7, 0xfc, 0xfc, 0xfc, 0xbe, 0x0f, 0x7a, 0xd6, 0x99, 0x60, 0xc6, 0x82, 0xe7, 0x1e, 0xdd,
	0x52, 0x09, 0x4c, 0x6b, 0x80, 0xde, 0x50, 0x3e, 0x28, 0x93, 0x2f, 0x1f, 0xe4, 0x7c, 0x11, 0x4e,
	0x86, 0x7d, 0x69, 0x8c, 0x3c, 0xc5, 0xb1, 0xb3, 0x62, 0xec, 0x03, 0x0f, 0x0b, 0x1f, 0x75, 0xc3,
	0xae, 0x34, 0xd2, 0x44, 0x8f, 0xea, 0x14, 0xd1, 0xd1, 0x27, 0x02, 0xbd, 0x19, 0xba, 0xa0, 0xde,
	0x29, 0xc1, 0x03, 0xce, 0x95, 0xd4, 0x19, 0x7e, 0x58, 0xa0, 0x0f, 0xf4, 0x16, 0x6c, 0x09, 0xef,
	0x06, 0x64, 0x9f, 0x1c, 0x5c, 0xcf, 0xaa, 0x23, 0x7d, 0x05, 0x3d, 0x6d, 0x0a, 0xcc, 0xb9, 0x44,
	0x1d, 0x72, 0xe1, 0xb0, 0x40, 0x1d, 0x14, 0x3f, 0xf5, 0x83, 0x2b, 0xfb, 0xe4, 0xa0, 0x33, 0xb9,
	0x93, 0x5e, 0xca, 0x92, 0x3e, 0x37, 0x05, 0x4e, 0x2b, 0xed, 0x6c, 0x2d, 0xcd, 0xba, 0xba, 0x05,
	0x1d, 0x7d, 0x26, 0xd0, 0x6d, 0x93, 0xd3, 0x37, 0xd0, 0x97, 0xc2, 0xe6, 0x4a, 0xfb, 0xc0, 0xb5,
	0xc0, 0xbf, 0x5e, 0xad, 0x93, 0x75, 0x26, 0x77, 0x37, 0x1e, 0x7d, 0x22, 0xec, 0x71, 0x23, 0x5e,
	0xfb, 0x3c, 0x4d, 0xb2, 0x3d, 0xd9, 0x46, 0x1c, 0xed, 0xc2, 0x4e, 0xfd, 0xa7, 0xb5, 0xef, 0xe8,
	0x05, 0xec, 0xb5, 0x9a, 0xd0, 0x47, 0x30, 0xf0, 0x4a, 0x6a, 0x2c, 0xd6, 0x71, 0xde, 0x63, 0xe0,
	0x05, 0x0f, 0xbc, 0xa9, 0xa9, 0x17, 0xf9, 0x3f, 0x77, 0x9f, 0x35, 0xec, 0xe8, 0x2b, 0x81, 0xfe,
	0x3f, 0x35, 0x7b, 0x6b, 0xb4, 0x47, 0x7a, 0x1b, 0x3a, 0xca, 0xe7, 0xdc, 0x5a, 0x67, 0x96, 0x58,
	0xd4, 0x46, 0xd7, 0x32, 0x50, 0x7e, 0xda, 0x20, 0xf4, 0x10, 0xb6, 0xe3, 0x24, 0x9b, 0x9a, 0x69,
	0x1a, 0x67, 0x9c, 0x3a, 0x2b, 0xd2, 0x79, 0xcd, 0x64, 0x8d, 0x82, 0x1e, 0xc2, 0x6e, 0x13, 0x51,
	0xa0, 0x0b, 0xb9, 0x38, 0xe1, 0x4a, 0x0f, 0xb6, 0xea, 0x6c, 0x3b, 0x91, 0xa8, 0x62, 0xcc, 0x2a,
	0x78, 0x22, 0xe1, 0xe6, 0x71, 0x55, 0xdd, 0x6c, 0x3a, 0x8f, 0x1b, 0x45, 0x5f, 0xc2, 0xd5, 0x2a,
	0x1a, 0xbd, 0xb7, 0xd1, 0x69, 0xfb, 0x86, 0x0c, 0xef, 0xff, 0x4f, 0x16, 0x7f, 0x78, 0xf4, 0xf8,
	0x6c, 0xc5, 0x92, 0xf3, 0x15, 0x4b, 0xbe, 0xaf, 0x58, 0x72, 0xb1, 0x62, 0xc9, 0xc7, 0x92, 0x91,
	0x6f, 0x25, 0x4b, 0xce, 0x4a, 0x46, 0xce, 0x4b, 0x46, 0x7e, 0x94, 0x8c, 0xfc, 0x2a, 0x59, 0x72,
	0x51, 0x32, 0xf2, 0xe5, 0x27, 0x4b, 0x5e, 0x5f, 0x5e, 0xea, 0xb7, 0xdb, 0xf5, 0xb2, 0x3e, 0xfc,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x0a, 0x26, 0x86, 0x04, 0x03, 0x00, 0x00,
}
